/**
 * agentsMdBuilders.ts — Constructores de AGENTS.md, copilot-instructions.md y docs/
 *
 * Funciones extraídas de extension.ts durante la modularización (ADR-014).
 */

import { DEFAULT_PRD_PATH } from './prdManager';

export interface GeneratedProjectFile {
	path: string;
	content: string;
}

// ── AGENTS.md ────────────────────────────────────────────────────────────────

export function buildAgentsMd(role: string, stack: string, project: string, checkpoints: string[], guardrails: string[], date: string): string {
	const stackLines     = stack ? stack.split(',').map(s => `- ${s.trim()}`).join('\n') : '- (define in Settings)';
	const checkpointList = checkpoints.length ? checkpoints.map((c, i) => `${i + 1}. ${c}`).join('\n') : '1. Delete files\n2. Modify DB schemas\n3. Change security config';
	const guardrailList  = guardrails.length  ? guardrails.map(g => `- ${g}`).join('\n')  : '- Never modify prd.json\n- Never delete files without confirmation';

	return `# AGENTS.md — Project Agent Manual

> **Project:** ${project || '(define in Settings → ralph-suite.agentProject)'}
> **Generated:** ${date} by Ralph Suite

## Role
You are a **${role}** working on this project.

**Stack:**
${stackLines}

## Rules (always follow)
${guardrailList}

## IDs and collaboration
- GitHub references use owner/repo#N; GitHub assigns N.
- ADR-NNN is reserved exclusively for decisions.
- A Ralph local ID is exactly the ID supplied by the backlog and runner context. Do not infer that ISSUE-001 means GitHub issue #1, and do not renumber or migrate IDs.
- The ralph-suite.syncIssue command maps GitHub to Ralph only through explicit github:#N or owner/repo#N labels. Never infer ISSUE-00N from GitHub #N; write only runtime .ralph, never prd.json.
- The documentary identity across repositories is repo + local ID; this does not implement a workspace feature.
- Only authorized commits are allowed.

## Checkpoints (stop and ask before these)
${checkpointList}

## Before starting any task, read:
- \`.agent/memories.md\` — accumulated project knowledge
- \`docs/project/architecture.md\` — architecture decisions
- \`docs/project/threat-model.md\` — security requirements
- \`docs/adr/\` — decision log
- \`${DEFAULT_PRD_PATH}\` — task backlog

Runtime lives in \`.ralph/\` (gitignored). If you write loop scratch, use \`.ralph/progress.md\`.

## Ralph context and ad hoc work
- Only a Ralph task with explicit Ralph task ID and workspace root may write .ralph/ signals.
- Ad hoc, analysis, review, documentation, and handoff requests do not require an ID and must not write .ralph/ signals.
- If a Ralph execution lacks its task ID or workspace root, ask for that context before running it.

## Completion protocol
For a Ralph task with the required context, and only after the full task scope and quality gates are complete:
1. Overwrite (not append) .ralph/task-<ID>-status with the single word: completed. Remove the previous status value first. The file must contain ONLY that word — no extra lines, no other content.
2. Write NOTA: <one line summary> to .ralph/task-<ID>-note.
Never write completion signals during review, rejection, or partial handoff. If writing either file fails, report the exact error and do not silently proceed.

## Testing
- Run existing tests before marking any task completed
- New features require tests
- Do not break passing tests

*Generated by Ralph Suite ${date}*
`;
}

// ── Copilot instructions ─────────────────────────────────────────────────────

export function buildCopilotInstructions(project: string, stack: string): string {
	return `# GitHub Copilot Instructions
> See [AGENTS.md](../AGENTS.md) for the full protocol.

**Project:** ${project || 'See AGENTS.md'}
**Stack:** ${stack || 'See AGENTS.md'}

## IDs and collaboration
- GitHub references use owner/repo#N; GitHub assigns N. ADR-NNN is reserved for decisions.
- Use the Ralph local ID exactly as provided by the backlog and runner context. Do not infer GitHub issue numbers, renumber IDs, or migrate them.
- The ralph-suite.syncIssue command maps GitHub to Ralph only through explicit github:#N or owner/repo#N labels. Never infer ISSUE-00N from GitHub #N; write only runtime .ralph, never prd.json.
- Ad hoc, analysis, review, documentation, and handoff work does not require an ID or .ralph signals. A Ralph execution without explicit task ID and workspace root must request that context.

## Critical Rules
1. Read \`.agent/memories.md\` before starting any task
2. Follow conventions already in the codebase
3. Tests required for new features
4. Never commit secrets — use environment variables
5. Commits only when explicitly authorized
6. Write completion signals only for Ralph tasks with explicit context, after all scope and gates pass
`;
}

// ── Plan files ───────────────────────────────────────────────────────────────

export function buildArquitecturaMd(project: string, stack: string, date: string): string {
	return `# Architecture — ${project || 'Project'}
> Last updated: ${date}

## Stack
${stack ? stack.split(',').map(s => `- ${s.trim()}`).join('\n') : '- (fill in)'}

## Structure
\`\`\`
/ (add your structure)
\`\`\`

## Key Decisions
- [Describe architecture and why]

## Conventions
- Naming: [snake_case / camelCase]
- Error handling: [describe]
- Config/secrets: [describe]

## Locked decisions (do not change without discussion)
- [list]
`;
}

export function buildSeguridadMd(project: string, date: string): string {
	return `# Security — ${project || 'Project'}
> Last updated: ${date}

## Secrets
- Never hardcode — use environment variables
- Document required vars:

| Variable | Purpose |
|----------|---------|
| (add) | |

## Auth
- [Describe mechanism]

## Checkpoints required before:
- Changing auth logic
- Adding public endpoints
- Modifying CORS
- Changing how secrets are loaded
`;
}

export function buildDecisionesMd(project: string, date: string): string {
	return `# ADR-001 — Project setup

**Project:** ${project || 'Project'}
**Date:** ${date} | **Status:** Accepted

**Decision:** Keep the agent index at root (\`AGENTS.md\`). Human docs live under \`docs/\` (\`docs/project/\` for architecture and threat model, \`docs/adr/\` for this log). Machine backlog is \`${DEFAULT_PRD_PATH}\`. Runtime stays in \`.ralph/\`.

**Consequences:**
- ✅ Single source of truth for each concern
- ⚠️ Keep \`docs/\` updated; do not scatter project files at the workspace root

---
*Add ADR-NNN for each significant technical decision.*
`;
}

export function buildStatusMd(project: string, date: string): string {
	return `# Status — ${project || 'Project'}
> Snapshot: ${date}

This file is a human snapshot, not the Kanban. The board reads \`${DEFAULT_PRD_PATH}\`.

## Current
- Setup generated by Ralph Suite.

## Next
- Fill architecture, threat model and the first backlog issues.
`;
}

export function buildImplementationPlanMd(project: string): string {
	return `# Implementation plan — ${project || 'Project'}

Optional human plan. This file does not replace \`prd.json\`.

The Kanban backlog remains \`${DEFAULT_PRD_PATH}\`.
`;
}

export function buildInitPromptText(
	goal: string,
	workspaceRoot: string,
	guardrails: string[],
	checkpoints: string[],
): string {
	const guardrailList  = guardrails.map(g => `- ${g}`).join('\n') || '- Never modify prd.json';
	const checkpointList = checkpoints.map((c, i) => `${i + 1}. ${c}`).join('\n') || '1. Delete files\n2. Modify DB schemas';
	const prdFile = `${workspaceRoot.replace(/\\/g, '/')}/${DEFAULT_PRD_PATH}`;

	return `You are a senior software architect helping set up a new project with the Ralph Suite workflow.

The user wants to build: **${goal}**

## Your job

1. Ask clarifying questions to understand the project fully (stack, features, constraints, security needs)
2. Once you have enough context, generate ALL of these files in one go:

### File 1: AGENTS.md (workspace root)
\`\`\`
# AGENTS.md — Project Agent Manual
> Project: [name] | Stack: [stack] | Generated: [date]

## Role
You are a Senior Software Engineer working on [project].
**Stack:** [list]

## Rules
${guardrailList}

## Checkpoints (stop and ask before these)
${checkpointList}

## Before starting any task, read:
- .agent/memories.md
- docs/project/architecture.md
- docs/project/threat-model.md
- docs/adr/
- ${DEFAULT_PRD_PATH}

## IDs and completion
- Use the backlog ID exactly as provided by the Ralph context. Do not infer a GitHub issue number from a local ID, renumber IDs, or migrate them.
- GitHub references use owner/repo#N, with N assigned by GitHub. ADR-NNN is only for decisions.
- The ralph-suite.syncIssue command maps GitHub to Ralph only through explicit github:#N or owner/repo#N labels. Never infer ISSUE-00N from GitHub #N; write only runtime .ralph, never prd.json.
- Ad hoc work does not require an ID or .ralph signals. A Ralph execution without explicit task ID and workspace root must request that context.
- For a Ralph execution with the required context, write the exact completed status and NOTA: note only after all scope and gates pass; never for review, rejection, or partial handoff.
\`\`\`

### File 2: .github/copilot-instructions.md
Brief — references AGENTS.md, lists 3 critical rules.

### File 3: docs/project/architecture.md
Real architecture decisions from the conversation.

### File 4: docs/project/threat-model.md
Security rules, secrets, auth, CORS for this project.

### File 5: docs/adr/ADR-001-project-setup.md
ADR-001 for stack choice. Further ADRs go in docs/adr/.

### File 6: docs/project/status.md
Short human snapshot — not the Kanban.

### File 7: docs/ralph/IMPLEMENTATION_PLAN.md
Optional human plan; it does not replace prd.json.

### File 8: ${DEFAULT_PRD_PATH}
\`\`\`json
{
  "project": "Name",
  "description": "Short description",
  "version": "1.0.0",
  "issues": [{
    "id": "ISSUE-001",
    "title": "...",
    "description": "...",
    "epic": "Setup",
    "priority": "P0",
    "status": "todo",
    "acceptanceCriteria": ["..."],
    "dependencies": [],
    "labels": []
  }]
}
\`\`\`
Rules: preserve each local backlog ID exactly, use P0>P1>P2>P3, and set the initial status to "todo". Do not infer GitHub issue numbers or add commits unless explicitly authorized.
CREATE the file at: ${prdFile}
Create parent directories if needed. Loop scratch belongs in .ralph/progress.md if you write any.

## Important
- Start with questions — do NOT generate files until you understand the project
- Generate ALL files at once when ready
- Workspace root: \`${workspaceRoot}\``;
}

export function buildGeneratedProjectFiles(
	role: string,
	stack: string,
	project: string,
	checkpoints: string[],
	guardrails: string[],
	date: string,
): GeneratedProjectFile[] {
	return [
		{ path: 'AGENTS.md', content: buildAgentsMd(role, stack, project, checkpoints, guardrails, date) },
		{ path: '.github/copilot-instructions.md', content: buildCopilotInstructions(project, stack) },
		{ path: 'docs/project/architecture.md', content: buildArquitecturaMd(project, stack, date) },
		{ path: 'docs/project/threat-model.md', content: buildSeguridadMd(project, date) },
		{ path: 'docs/project/status.md', content: buildStatusMd(project, date) },
		{ path: 'docs/adr/ADR-001-project-setup.md', content: buildDecisionesMd(project, date) },
		{ path: 'docs/ralph/IMPLEMENTATION_PLAN.md', content: buildImplementationPlanMd(project) },
	];
}
