/**
 * agentsMdBuilders.ts — Constructores de AGENTS.md, copilot-instructions.md y planes
 *
 * Funciones extraídas de extension.ts durante la modularización (ADR-014).
 */

// ── AGENTS.md ────────────────────────────────────────────────────────────────

export function buildAgentsMd(role: string, stack: string, project: string, checkpoints: string[], guardrails: string[], date: string): string {
	const stackLines     = stack ? stack.split(',').map(s => `- ${s.trim()}`).join('\n') : '- (define in Settings)';
	const checkpointList = checkpoints.length ? checkpoints.map((c, i) => `${i + 1}. ${c}`).join('\n') : '1. Delete files\n2. Modify DB schemas\n3. Change security config';
	const guardrailList  = guardrails.length  ? guardrails.map(g => `- ${g}`).join('\n')  : '- Never modify prd.json\n- Never delete files without confirmation';

	return `# AGENTS.md — Project Agent Manual

> **Project:** ${project || '(define in Settings → ralph-suite.agentProject)'}
> **Generated:** ${date} by Ralph Suite

## Role
You are a **${role}** working on this project.

**Stack:**
${stackLines}

## Rules (always follow)
${guardrailList}

## Checkpoints (stop and ask before these)
${checkpointList}

## Before starting any task, read:
- \`.agent/memories.md\` — accumulated project knowledge
- \`plans/arquitectura.md\` — architecture decisions
- \`plans/seguridad.md\` — security requirements
- \`plans/decisiones.md\` — decision log
- \`prd.json\` — task backlog

## Completion protocol
1. Overwrite (not append) \`.ralph/task-<ID>-status\` with the single word: \`completed\`
   File must contain ONLY that word — no extra lines, no other content.
2. Write \`NOTA: <one line summary>\` → \`.ralph/task-<ID>-note\`
Then stop and wait. Do not ask follow-up questions.

## Testing
- Run existing tests before marking any task completed
- New features require tests
- Do not break passing tests

*Generated by Ralph Suite ${date}*
`;
}

// ── Copilot instructions ─────────────────────────────────────────────────────

export function buildCopilotInstructions(project: string, stack: string): string {
	return `# GitHub Copilot Instructions
> See [AGENTS.md](../AGENTS.md) for the full protocol.

**Project:** ${project || 'See AGENTS.md'}
**Stack:** ${stack || 'See AGENTS.md'}

## Critical Rules
1. Read \`.agent/memories.md\` before starting any task
2. Follow conventions already in the codebase
3. Tests required for new features
4. Never commit secrets — use environment variables
5. Write completion signals when done
`;
}

// ── Plan files ───────────────────────────────────────────────────────────────

export function buildArquitecturaMd(project: string, stack: string, date: string): string {
	return `# Architecture — ${project || 'Project'}
> Last updated: ${date}

## Stack
${stack ? stack.split(',').map(s => `- ${s.trim()}`).join('\n') : '- (fill in)'}

## Structure
\`\`\`
/ (add your structure)
\`\`\`

## Key Decisions
- [Describe architecture and why]

## Conventions
- Naming: [snake_case / camelCase]
- Error handling: [describe]
- Config/secrets: [describe]

## Locked decisions (do not change without discussion)
- [list]
`;
}

export function buildSeguridadMd(project: string, date: string): string {
	return `# Security — ${project || 'Project'}
> Last updated: ${date}

## Secrets
- Never hardcode — use environment variables
- Document required vars:

| Variable | Purpose |
|----------|---------|
| (add) | |

## Auth
- [Describe mechanism]

## Checkpoints required before:
- Changing auth logic
- Adding public endpoints
- Modifying CORS
- Changing how secrets are loaded
`;
}

export function buildDecisionesMd(project: string, date: string): string {
	return `# Decision Log — ${project || 'Project'}

## ADR-001: Project setup
**Date:** ${date} | **Status:** Accepted

**Decision:** Use prd.json for tasks, .agent/memories.md for context, plans/ for architecture docs.

**Consequences:**
- ✅ Single source of truth
- ⚠️ Requires keeping plans/ updated

---
*Add ADR-NNN for each significant technical decision.*
`;
}
